# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rOCUKKiOuT5DTNSvUUnBFWnrjFQqkw2u

**Create a K-means clustering algorithm to group customers of a retail store based on their purchase history.**
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

df = pd.read_csv("Mall_Customers.csv")
print(df.head())

X = df[['Annual Income (k$)', 'Spending Score (1-100)']]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
inertia = []
k_range = range(1, 11)

for k in k_range:
  km = KMeans(n_clusters=k, random_state=42)
  km.fit(X_scaled)
  inertia.append(km.inertia_)

optimal_k = 5
kmeans = KMeans(n_clusters=optimal_k, random_state=42)
clusters = kmeans.fit_predict(X_scaled)
df['Cluster'] = clusters

kmeans = KMeans(n_clusters=k, random_state=42)
kmeans.fit(X_scaled)

cluster_labels = kmeans.predict(X_scaled)
df['Cluster'] = cluster_labels
print(df.head())

print(df)

print("Cluster Centers (scaled):")
print(kmeans.cluster_centers_)

original_centers = scaler.inverse_transform(kmeans.cluster_centers_)
print("Cluster Centers (original scale):")
print(original_centers)

# Add cluster labels to DataFrame
df['Cluster'] = clusters

# Save the new DataFrame with clusters to a CSV file
df.to_csv("Mall_Customers_with_Clusters.csv", index=False)